# 02 — Experiment Analysis

A full experiment readout, in the order a real experimentation platform
would run it:

1. **Trust check first** (Sample Ratio Mismatch) — before reading any
   result, verify the assignment mechanism delivered the designed split.
2. **Named comparisons** mirroring the source case study's 4 Key Insights,
   with 95% CIs and FDR correction.
3. **Direction concordance vs. ground truth** — a diagnostic only a
   simulation can run: which non-significant cells are power problems,
   and which are correctly null?
4. **Power & MDE table** — how big should this experiment have been, and
   what was it ever capable of detecting at its actual size?
5. **Adequately-powered rerun** — the same DGP at the sample size the
   power analysis prescribes, closing the loop on the diagnosis.

See `experiment_analysis.py` for full docstrings.

In [1]:
import os
import sys
from pathlib import Path

# Anchor all relative paths to THIS file's location, not the caller's cwd —
# so the notebook works whether run via Jupyter (kernel cwd = notebooks/) or
# as a script from anywhere (e.g. `python notebooks/02_....py` from repo root).
try:
    NOTEBOOK_DIR = Path(__file__).resolve().parent
except NameError:  # __file__ undefined inside a notebook kernel
    NOTEBOOK_DIR = Path.cwd()
os.chdir(NOTEBOOK_DIR)
sys.path.insert(0, str(NOTEBOOK_DIR.parent))

import pandas as pd

from data_generation import VoucherDGP
from experiment_analysis import (
    run_named_comparisons,
    fit_interaction_models,
    srm_check,
    power_mde_table,
    direction_concordance,
    NAMED_COMPARISONS,
    TIERS_ASC,
)

experiment_log = pd.read_csv("../data/processed/experiment_log.csv")
dgp = VoucherDGP(calibration_path="../data/raw_benchmarks/case_summary_tables.csv")

## 1. Trust check: Sample Ratio Mismatch (SRM)

Chi-square test per tier against the designed uniform 1/7 allocation,
with the industry-standard strict alarm threshold (p < 0.001). A failed
SRM check invalidates every downstream number — which is why it runs
BEFORE any result is read, not after.

In [2]:
srm = srm_check(experiment_log)
srm

    tier  n_users  n_conditions     chi2  p_value  srm_alarm
0   0-29    83308             7  8.77385  0.18670      False
1  30-69    36988             7  3.00984  0.80761      False
2  70-79    17302             7  7.48122  0.27862      False
3  80-89    15700             7  4.87185  0.56035      False
4  90-99     7598             7  4.04422  0.67069      False
5    100    39104             7  5.46041  0.48625      False

In [3]:
assert not srm["srm_alarm"].any(), "SRM detected — do not read results until assignment is debugged"
print("SRM check passed for all tiers — safe to read results.")

SRM check passed for all tiers — safe to read results.

## 2. Named comparisons (mirrors the source case study's 4 Key Insights)

Two-proportion z-tests (order rate) and Welch t-tests (profit/user) per
tier, now with 95% CIs on the absolute difference, BH-FDR corrected
within each metric family.

In [4]:
comparisons = run_named_comparisons(experiment_log)
comparisons.to_csv("../outputs/named_comparisons.csv", index=False)
comparisons[
    ["comparison", "tier", "metric", "abs_diff", "ci_low", "ci_high", "pct_lift", "q_value", "significant"]
]

,comparison,tier,metric,abs_diff,ci_low,ci_high,pct_lift,q_value,significant
0,voucher_vs_none,0-29,order_rate,0.00281,-0.00416,0.00979,3.49602,0.98064,False
1,voucher_vs_none,0-29,profit_per_user,0.00785,-0.00648,0.02218,5.10436,0.56557,False
2,voucher_vs_none,30-69,order_rate,-0.00547,-0.01695,0.00599,-5.34415,0.98064,False
3,voucher_vs_none,30-69,profit_per_user,-0.02503,-0.04380,-0.00625,-15.16982,0.17560,False
4,voucher_vs_none,70-79,order_rate,0.02134,0.00554,0.03723,27.07146,0.19365,False
5,voucher_vs_none,70-79,profit_per_user,0.00385,-0.01391,0.02161,4.16459,0.89478,False
6,voucher_vs_none,80-89,order_rate,0.01436,-0.00269,0.03145,16.50106,0.58994,False
7,voucher_vs_none,80-89,profit_per_user,-0.00096,-0.01571,0.01379,-1.25217,0.97250,False
8,voucher_vs_none,90-99,order_rate,0.02693,0.00104,0.05299,29.59787,0.32933,False
9,voucher_vs_none,90-99,profit_per_user,0.01066,-0.00504,0.02636,19.77420,0.54987,False
10,voucher_vs_none,100,order_rate,0.00201,-0.00469,0.00872,6.06952,0.98064,False
11,voucher_vs_none,100,profit_per_user,-0.00570,-0.01168,0.00028,-18.19314,0.36913,False
12,minspend_299_vs_249,0-29,order_rate,-0.00116,-0.00814,0.00582,-1.39604,0.98064,False
13,minspend_299_vs_249,0-29,profit_per_user,-0.00959,-0.02373,0.00454,-5.93365,0.54987,False
14,minspend_299_vs_249,30-69,order_rate,-0.00042,-0.01166,0.01081,-0.43695,0.98064,False
15,minspend_299_vs_249,30-69,profit_per_user,0.00226,-0.01518,0.01971,1.61561,0.95935,False
16,minspend_299_vs_249,70-79,order_rate,-0.00551,-0.02205,0.01099,-5.50471,0.98064,False
17,minspend_299_vs_249,70-79,profit_per_user,0.00477,-0.01297,0.02251,4.95831,0.89478,False
18,minspend_299_vs_249,80-89,order_rate,-0.00051,-0.01822,0.01723,-0.50505,0.98064,False
19,minspend_299_vs_249,80-89,profit_per_user,0.01334,-0.00213,0.02882,17.57010,0.42117,False
20,minspend_299_vs_249,90-99,order_rate,0.01224,-0.01548,0.03979,10.38171,0.98064,False
21,minspend_299_vs_249,90-99,profit_per_user,0.01702,-0.00042,0.03447,26.35605,0.36913,False
22,minspend_299_vs_249,100,order_rate,0.00025,-0.00658,0.00711,0.72271,0.98064,False
23,minspend_299_vs_249,100,profit_per_user,0.00354,-0.00212,0.00921,13.82487,0.56557,False
24,copay_9_vs_0,0-29,order_rate,0.00042,-0.00658,0.00742,0.50762,0.98064,False
25,copay_9_vs_0,0-29,profit_per_user,0.00019,-0.01434,0.01473,0.12046,0.97904,False
26,copay_9_vs_0,30-69,order_rate,0.00371,-0.00766,0.01508,3.82370,0.98064,False
27,copay_9_vs_0,30-69,profit_per_user,0.00740,-0.01031,0.02511,5.28808,0.76176,False
28,copay_9_vs_0,70-79,order_rate,0.00150,-0.01543,0.01846,1.49512,0.98064,False
29,copay_9_vs_0,70-79,profit_per_user,0.01037,-0.00776,0.02850,10.77513,0.56557,False
30,copay_9_vs_0,80-89,order_rate,0.00396,-0.01388,0.02183,3.90859,0.98064,False
31,copay_9_vs_0,80-89,profit_per_user,0.01253,-0.00263,0.02769,16.49647,0.42117,False
32,copay_9_vs_0,90-99,order_rate,-0.00935,-0.03626,0.01745,-7.92701,0.98064,False
33,copay_9_vs_0,90-99,profit_per_user,0.00071,-0.01571,0.01714,1.10669,0.97250,False
34,copay_9_vs_0,100,order_rate,-0.00200,-0.00872,0.00471,-5.70902,0.98064,False
35,copay_9_vs_0,100,profit_per_user,0.00133,-0.00414,0.00680,5.19841,0.89478,False
36,count_3_vs_1,0-29,order_rate,-0.00299,-0.00985,0.00387,-3.74622,0.98064,False
37,count_3_vs_1,0-29,profit_per_user,-0.00786,-0.02214,0.00643,-5.00459,0.56557,False
38,count_3_vs_1,30-69,order_rate,-0.01265,-0.02439,-0.00092,-11.30519,0.32933,False
39,count_3_vs_1,30-69,profit_per_user,-0.02380,-0.04290,-0.00469,-13.70950,0.17560,False
40,count_3_vs_1,70-79,order_rate,0.00021,-0.01681,0.01719,0.20247,0.98064,False
41,count_3_vs_1,70-79,profit_per_user,-0.00634,-0.02642,0.01373,-5.36688,0.89478,False
42,count_3_vs_1,80-89,order_rate,-0.00352,-0.02026,0.01313,-3.88563,0.98064,False
43,count_3_vs_1,80-89,profit_per_user,0.00060,-0.01289,0.01410,0.89138,0.97250,False
44,count_3_vs_1,90-99,order_rate,0.00115,-0.02296,0.02531,1.30475,0.98064,False
45,count_3_vs_1,90-99,profit_per_user,0.00251,-0.01114,0.01616,5.47566,0.90725,False
46,count_3_vs_1,100,order_rate,0.00076,-0.00599,0.00750,2.28242,0.98064,False
47,count_3_vs_1,100,profit_per_user,-0.00146,-0.00796,0.00504,-4.71709,0.89478,False

**Headline: 0 of 48 comparisons are significant after FDR correction.**
The CI columns make the reason visible without any p-value: nearly every
interval spans zero. The next two sections separate the two very
different explanations hiding inside that headline number.

## 3. Direction concordance vs. ground truth

Because the true effects were calibrated into the DGP, every comparison
can be classified: does the observed sign match the true sign, or was it
flipped by sampling noise? And critically — which cells have a
*negligible* true effect, where non-significance is the CORRECT outcome
rather than a power failure?

In [5]:
concordance = direction_concordance(comparisons, dgp)
concordance["true_effect"].value_counts()

true_effect
positive      27
negative      16
negligible     5
Name: count, dtype: int64

In [6]:
non_negligible = concordance[concordance["true_effect"] != "negligible"]
agreement_rate = non_negligible["sign_agrees"].mean()
print(
    f"Sign agreement among non-negligible true effects: "
    f"{agreement_rate:.0%} ({int(non_negligible['sign_agrees'].sum())}/{len(non_negligible)})"
)
concordance[concordance["sign_agrees"] == False]  # noqa: E712 — the sign-flipped cells

Sign agreement among non-negligible true effects: 70% (30/43)

,comparison,tier,metric,true_diff,observed_diff,true_effect,sign_agrees
2,voucher_vs_none,30-69,order_rate,0.00300,-0.00547,positive,False
5,voucher_vs_none,70-79,profit_per_user,-0.00300,0.00384,negative,False
7,voucher_vs_none,80-89,profit_per_user,0.00100,-0.00097,positive,False
12,minspend_299_vs_249,0-29,order_rate,0.00100,-0.00116,positive,False
22,minspend_299_vs_249,100,order_rate,-0.00100,0.00025,negative,False
25,copay_9_vs_0,0-29,profit_per_user,-0.00051,0.00019,negative,False
28,copay_9_vs_0,70-79,order_rate,-0.00116,0.00150,negative,False
30,copay_9_vs_0,80-89,order_rate,-0.00837,0.00396,negative,False
33,copay_9_vs_0,90-99,profit_per_user,-0.00140,0.00072,negative,False
36,count_3_vs_1,0-29,order_rate,0.00100,-0.00299,positive,False
37,count_3_vs_1,0-29,profit_per_user,0.00107,-0.00786,positive,False
41,count_3_vs_1,70-79,profit_per_user,0.00099,-0.00634,positive,False
42,count_3_vs_1,80-89,order_rate,0.00400,-0.00351,positive,False

Interpretation: most estimates point the right way, a substantial
minority are sign-flipped by noise — exactly the behavior expected from
an underpowered experiment, and a concrete warning against reading
individual cell directions at this sample size. The negligible-effect
cells are NOT failures: for them, "not significant" is the truth.

## 4. Power & MDE table (order-rate metric, Bonferroni-corrected)

Two complementary views per comparison x tier:
- **required_n_per_arm** — how big the experiment needed to be to detect
  the observed lift at 80% power.
- **mde_pct_lift** — the smallest lift detectable at the ACTUAL per-arm
  size (the standard experimentation-platform readout).

In [7]:
power_table = power_mde_table(comparisons, experiment_log)
power_table.to_csv("../outputs/power_mde_table.csv", index=False)
power_table

,comparison,tier,observed_pct_lift,current_n_per_arm,required_n_per_arm,mde_pct_lift,status
0,voucher_vs_none,0-29,3.5,11794,291900.0,17.9,underpowered
1,voucher_vs_none,30-69,-5.3,5185,92100.0,23.9,underpowered
2,voucher_vs_none,70-79,27.1,2466,5500.0,41.4,underpowered
3,voucher_vs_none,80-89,16.5,2258,12700.0,40.9,underpowered
4,voucher_vs_none,90-99,29.6,1060,4000.0,60.1,underpowered
5,voucher_vs_none,100,6.1,5650,250800.0,43.7,underpowered
6,minspend_299_vs_249,0-29,-1.4,11971,1724600.0,17.4,underpowered
7,minspend_299_vs_249,30-69,-0.4,5323,14963800.0,24.4,underpowered
8,minspend_299_vs_249,70-79,-5.5,2466,88900.0,35.9,underpowered
9,minspend_299_vs_249,80-89,-0.5,2210,10649500.0,37.7,underpowered
10,minspend_299_vs_249,90-99,10.4,1060,22300.0,51.0,underpowered
11,minspend_299_vs_249,100,0.7,5543,16224300.0,42.7,underpowered
12,copay_9_vs_0,0-29,0.5,11984,13157000.0,17.4,underpowered
13,copay_9_vs_0,30-69,3.8,5276,199200.0,24.5,underpowered
14,copay_9_vs_0,70-79,1.5,2410,1243200.0,36.3,underpowered
15,copay_9_vs_0,80-89,3.9,2230,181300.0,37.6,underpowered
16,copay_9_vs_0,90-99,-7.9,1060,35400.0,51.0,underpowered
17,copay_9_vs_0,100,-5.7,5619,252000.0,42.4,underpowered
18,count_3_vs_1,0-29,-3.7,11653,247900.0,18.1,underpowered
19,count_3_vs_1,30-69,-11.3,5265,18200.0,22.5,underpowered
20,count_3_vs_1,70-79,0.2,2448,64803700.0,35.3,underpowered
21,count_3_vs_1,80-89,-3.9,2177,201000.0,40.8,underpowered
22,count_3_vs_1,90-99,1.3,1073,1874200.0,60.8,underpowered
23,count_3_vs_1,100,2.3,5501,1743100.0,44.3,underpowered

In [8]:
worked = power_table[
    (power_table["comparison"] == "voucher_vs_none") & (power_table["tier"] == "90-99")
].iloc[0]
print(
    f"Worked example — 90-99% tier, voucher_vs_none:\n"
    f"  observed lift {worked['observed_pct_lift']}% vs. MDE {worked['mde_pct_lift']}% "
    f"at n={worked['current_n_per_arm']:,}/arm\n"
    f"  -> the observed effect is ~half the smallest effect this cell could detect;\n"
    f"     required n/arm to detect it: {worked['required_n_per_arm']:,.0f}"
)

Worked example — 90-99% tier, voucher_vs_none:
  observed lift 29.6% vs. MDE 60.1% at n=1,060/arm
  -> the observed effect is ~half the smallest effect this cell could detect;
     required n/arm to detect it: 4,000

## 5. Adequately-powered rerun

The naive fix is scaling total N until the smallest key tier hits its
required per-arm size: the 90-99% tier is 3.7% of the population, so
4,000/arm x 7 arms / 3.7% ≈ **750,000 users**. (A real design would use
stratified oversampling of the small tiers to hit the same power at
roughly half that total — noted here, not implemented, since the point
of this section is closing the loop on the power diagnosis.)

In [9]:
big_log = dgp.simulate_users(n_users=750_000, seed=7)
big_comparisons = run_named_comparisons(big_log)

n_sig_small = int(comparisons["significant"].sum())
n_sig_big = int(big_comparisons["significant"].sum())
print(f"Significant after FDR at N=200k: {n_sig_small} / 48")
print(f"Significant after FDR at N=750k: {n_sig_big} / 48")

Significant after FDR at N=200k: 0 / 48
Significant after FDR at N=750k: 7 / 48

In [10]:
big_comparisons[big_comparisons["significant"]][
    ["comparison", "tier", "metric", "pct_lift", "q_value"]
]

             comparison   tier           metric  pct_lift  q_value
3       voucher_vs_none  30-69  profit_per_user  -9.44234  0.03141
4       voucher_vs_none  70-79       order_rate  18.75052  0.00287
10      voucher_vs_none    100       order_rate  16.62424  0.03698
22  minspend_299_vs_249    100       order_rate -13.21206  0.03698
32         copay_9_vs_0  90-99       order_rate -16.74668  0.03698
43         count_3_vs_1  80-89  profit_per_user  21.94355  0.00282
45         count_3_vs_1  90-99  profit_per_user  23.69652  0.04889

Significance emerges exactly where the power analysis predicted —
in the cells with large true effects — while the negligible-true-effect
cells correctly stay null even at 3.75x the sample. This closes the
loop: the N=200k non-results were a power problem for the big effects
and the right answer for the null ones, and the experiment-design
takeaway is quantified (750k naive, or less with stratified
oversampling of the 90-99% tier).

## 6. Interaction regression (tier x condition), cross-check

In [11]:
order_summary, profit_summary = fit_interaction_models(experiment_log)
print("Order (logit) — top 10 terms by |coef|:")
order_summary.reindex(order_summary["coef"].abs().sort_values(ascending=False).index).head(10)

Order (logit) — top 10 terms by |coef|:

                                            term     coef  std_err  p_value
0                                      Intercept -2.43605  0.03385  0.00000
5                                 C(tier)[T.100] -0.93859  0.08171  0.00000
38   C(tier)[T.70-79]:C(condition)[T.s0_m199_c1]  0.41548  0.10921  0.00014
35   C(tier)[T.90-99]:C(condition)[T.s0_m299_c3]  0.37999  0.14538  0.00895
13  C(tier)[T.70-79]:C(condition)[T.s19_m199_c3]  0.35387  0.10962  0.00125
28  C(tier)[T.70-79]:C(condition)[T.s19_m199_c1]  0.31018  0.10991  0.00477
1                               C(tier)[T.30-69]  0.26533  0.05696  0.00000
20   C(tier)[T.90-99]:C(condition)[T.s0_m249_c3]  0.25191  0.14974  0.09249
23   C(tier)[T.70-79]:C(condition)[T.s9_m249_c3]  0.23657  0.11034  0.03203
18   C(tier)[T.70-79]:C(condition)[T.s0_m249_c3]  0.22559  0.11018  0.04061

In [12]:
print("Profit (OLS) — top 10 terms by |coef|:")
profit_summary.reindex(profit_summary["coef"].abs().sort_values(ascending=False).index).head(10)

Profit (OLS) — top 10 terms by |coef|:

                                            term     coef  std_err  p_value
0                                      Intercept  0.15385  0.00407  0.00000
5                                 C(tier)[T.100] -0.12250  0.00715  0.00000
4                               C(tier)[T.90-99] -0.09992  0.01399  0.00000
3                               C(tier)[T.80-89] -0.07693  0.01014  0.00000
2                               C(tier)[T.70-79] -0.06146  0.00965  0.00000
17   C(tier)[T.30-69]:C(condition)[T.s0_m249_c3] -0.03288  0.01035  0.00149
35   C(tier)[T.90-99]:C(condition)[T.s0_m299_c3]  0.02943  0.01959  0.13300
22   C(tier)[T.30-69]:C(condition)[T.s9_m249_c3] -0.02567  0.01036  0.01322
13  C(tier)[T.70-79]:C(condition)[T.s19_m199_c3]  0.02417  0.01368  0.07737
28  C(tier)[T.70-79]:C(condition)[T.s19_m199_c1]  0.02265  0.01375  0.09951